### ISSUE TITLE
Make url target blank when contribution number is been clicked.

### ISSUE THREAD

**Issue by Rodriq** [lolimay/GSoC-Contribution-Leaderboard-Node#1]
If I have 2 PRs, when I click on the number, it shouldn't open on the same page.

**Comment by lolimay** [comment]
Do you mean that it should open in the new tab?

**Comment by lolimay** [comment]
> If I have 2 PRs, when I click on the number, it shouldn't open on the same page.

Do you mean that it should open in the new tab?

**Comment by lolimay** [comment]
Yeah, it's a good idea! I'll add this feature soon :)

**Comment by lolimay** [comment]
Implemented via  eb076d5
